### PR TITLE
Don't try to be responsive

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by kosssi** [comment]
why ?

**Comment by frankrousseau** [comment]
Same remark @nono. Can you add more explanation to your PR (why and what is changed)?

**Comment by nono** [comment]
It makes things look weird on desktop. The menu takes the full screen and is not something usual on desktop.

**Comment by nono** [comment]
Travis is in a bad day. Many tests had timeout. I've restarted them.

**Pull request merged**
