### PR TITLE
feat: Add i18n for the Netherlands

### PR DESCRIPTION
**Pull request by enguerran**
Add Dutch language generated by transifex: https://www.transifex.com/cozy/cozy-desktop/language/nl/

### CODE REVIEW

**Comment by enguerran** [comment]
I can't understand why `tx pull` fetch a `nl_NL.json` file.
But there already is a `nl.json` file.

Does someone knows something?

**Comment by nono** [comment]
@enguerran in the localization world, it's possible to have a translation file for a language (like `fr`), and to have specialized version for a country (`fr_FR` for french language in France, and `fr_CA` for french language in Canada). Transifex allows to have both, and some of our contributors have made a translation for dutch (`nl`) and others (or the same?) have made a translation for dutch in Netherlands. We should probably keep only one of those, and remove the other on transifex.

**Comment by taratatach** [comment]
La 2ème version a l'air d'être la bonne (des mots en double dans la première n'y sont pas présents, de l'anglais est remplacé par du néerlandais, …).
Je pense qu'on peut donc prendre celle-ci et supprimer l'autre.

**Comment by taratatach** [comment]
The localisation file was merged in another PR.

**Pull request closed without merging**
