### PR TITLE
Conflicts

### PR DESCRIPTION
**Pull request by nono**
This PR enables the 2-ways synchronization. Of course, a lot of works has been done for detecting and resolving conflicts. It's not perfect, but I have to advance on another big feature (detecting files moves&renames on the local file system) before fixing the last issues.

So, this PR can be merged now!

### CODE REVIEW

**Comment by nono** [comment]
Yeah, a green build on Travis \o/

**Comment by frankrousseau** [comment]
This PR is mega huge and will be hard to review. For businness reason, it's better to merge it directly. But keep in mind that this code will probably require continuous improvement: adding comments, removing typos, etc.

**Comment by nono** [comment]
@frankrousseau I disagree. It's really possible to do code review on it. The 4 first commits were from a previous PR, more than one week ago, so I hoped they were merged before this PR. And most of the code that is removed / added is tests. If you ignore them, you have some documentation and maybe 200 lines of "true" code to review.

**Comment by frankrousseau** [comment]
Yes, but we don't have people available to perform it. Moreover, it's better to ship this feature now than in the middle of the next sprint.

**Comment by frankrousseau** [comment]
I'll call you tomorrow to see what could be done next time.

**Pull request merged**
