### PR TITLE
Update doc linux.md

### PR DESCRIPTION
**Pull request by Picus13**
Please make sure the following boxes are checked:

- [ ] PR is not too big
- [ ] it improves UX & DX in some way
- [ ] it includes unit tests matching the implementation changes
- [ ] it includes scenarios matching a new behaviour or has been manually tested
- [ ] it includes relevant documentation

### CODE REVIEW

**Comment by taratatach** [comment]
Hi @Picus13!

Thank you for your contribution. Could you be a bit more specific about the bug you found on Debian 10?
This is probably something that can be fixed :).

**Comment by Picus13** [comment]
Hello @taratatach,

I think the bug comes from *Topicons Plus* more than *Cozy Desktop*.

For more details on the bug, when I launch Cozy, the icon is fine in my Dock and in my toolbar, but if I click on either one or the other I don't have access to any UI. The sync remains effective, but I don't have access to any menu :cry:

**Comment by taratatach** [comment]
Hi @Picus13,

I've installed a Debian 10 to test it myself along with the Topicons Redux extension which seems to be the maintained extension, available for users of Gnome Shell v3.16+ (so Debian 10 users included).

The systray icon is display and is clickable but you have to click a few pixels above the icon or a few pixels below.
Like you said, it is not a Cozy Desktop bug but rather a combination of Topicons and/or Gnome Shell bugs. If the issue is within Gnome itself it's unlikely to be fixed as they've dropped support for systray icons (which is the very reason of the existence of Topicons).

I'm sorry I cannot be of any more help here.

**Comment by nono** [comment]
Ping @taratatach

**Comment by nono** [comment]
Ping @taratatach

**Comment by taratatach** [comment]
@Picus13 thank you for pointing out the app works on Debian Buster. I'm closing this PR in favor of https://github.com/cozy-labs/cozy-desktop/pull/1742 which adds other changes to this documentation page.

**Pull request closed without merging**
