### PR TITLE
Big refactoring for readonly mode

### PR DESCRIPTION
**Pull request by nono**
Hi,

this is a very large refactoring. It can be merged now. It implements the readonly mode, where cozy-desktop copies files and folders from a remote cozy to a local folder.

### CODE REVIEW

**Comment by Kloadut** [comment]
Nice one :-) I'll take a look

**Comment by nono** [comment]
@frankrousseau can you merge this PR? I'll start a new one for the write-only mode.

**Comment by frankrousseau** [comment]
Thank  you @nono. Before starting the write-only mode. Can you make sure that version is published?

**Comment by nono** [comment]
@frankrousseau I'm not sure what you expect from me. Is it to publish on npm? If yes, I don't have the credentials for that.

**Pull request merged**
